config/routes.rb
require 'sidekiq/web'
Liki::Application.routes.draw do

  root to: 'nodes#root'

  concern :position do
    put :up, on: :member
    put :down, on: :member
  end

  resources :nodes, concerns: :position, path: 'p' do
    get :admin, on: :member
    post :admin, on: :member
    resources :nodes, path: 'p', only: :new
    resources :followings, path: 'f', only: :index
    resource :document, path: 'doc'
    resource :task, path: 'tarea'
    resource :event, path: 'evento', only: [:show, :new]
    resources :comments, path: 'comentarios'
  end

  resources :users, path: 'u'
  resources :members, path: 'm'
  resources :spaces
  resources :activities, path: 'a'
  resources :access
  resources :followings, path: 'f', only: [:create, :destroy]
  resources :photos, path: 'fotos'
  resources :photo_tags, path: 'ptag'
  resources :prototypes, path: 'tipos'

  get '/calendario(/:y(/:m))' => 'events#index', as: :calendar,
    constraints: {y: /\d{4}/, m: /\d{1,2}/}
  resources :events, path: 'calendario', except: [:index]
  get 'mapa' => 'explorer#map', as: :map


  resource :inbox, controller: 'inbox', only: [:show,:create]

  get 'novedades' => 'nodes#index', as: :recent
  get 'buscar' => 'explorer#search', as: :search

  resources :sessions, path: 's'
  get 'entrar(/:id)' => 'sessions#new', as: :login
  get 'salir' => 'sessions#destroy', as: :logout
  get 'enter/:id', to: 'sessions#enter', as: :enter
  get 'user_level/:id', to: 'sessions#user_level'
  get 'visit/:id', to: 'sessions#visit', as: :visit
  post 'invitacion', to: 'sessions#send_token', as: :send_token

  mount Sidekiq::Web, at: '/sidekiq'

  get '404' => 'site#error404'
  get '500' => 'site#error500'
  get 'mmmm', to: 'site#access_denied', as: :access_denied
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  belongs_to :space, counter_cache: true

  has_many :photo_tags, dependent: :delete_all
  has_many :photos, -> { order('created_at DESC') }, 
    through: :photo_tags

  has_many :taggings, foreign_key: 'tag_id', dependent: :delete_all
  has_many :taggeds, through: :taggings

  has_one :event

  include HasMentions
  include HasFollowers
  include HasActivity
  include HasAccesses
  include HasPrototype
  include HasComments

  validates_presence_of :user_id, :space_id
  validates_presence_of :title
  validates_uniqueness_of :title, scope: :space_id, 
    case_sensitive: false

  has_ancestry orphan_strategy: :restrict
  acts_as_list scope: [:space_id, :ancestry]
  include FriendlyId
  friendly_id :title, use: :scoped, scope: :space
  mount_uploader :document, DocumentUploader
  acts_as_gmappable process_geocoding: :geocode?, checker: :geocoded

  before_validation :set_space_id

  def profile?
    space.member(self.user).try(:node_id) == self.id
  end

  def ordered_children
    self.proto.order(self.children)
  end

  def document_title
    File.basename(document.url)
  end

  def gmaps4rails_address
    "#{self.map_address}, spain"
  end

  def geocode?
    self.map_address.present?
  end

  protected
  def set_space_id
    self.space_id = self.parent.space_id if self.parent
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_filter :require_user, except: [:root, :show]
  respond_to :html

  def root
    service.show(current_space.node_id)
    @node = service.node
    render action: 'show'
  end

  def index
    @root = current_space.node
  end

  def show
    begin
      service.show(params[:id])
      respond_with @node = service.node
    rescue ActiveRecord::RecordNotFound
      title = params[:id].camelcase.gsub(/-/, ' ')
      redirect_to new_node_path(t: title, p: params[:p])
    end
  end


  def new
    parent_id = params[:node_id] || params[:p]
    @node = service.new(params[:t], parent_id, params[:proto])
    respond_with @node = service.node
  end

  def edit
    service.edit(params[:id])
    respond_with @node = service.node
  end

  def create
    service.create(node_params)
    respond_with @node = service.node
  end

  def update
    service.update(params[:id], node_params)
    respond_with @node = service.node
  end

  def destroy
    service.destroy(params[:id])
    redirect_to (service.node.try(:parent) || root_path)
  end

  def admin
    @access_form = AccessFormPresenter.new
    @node_admin_form = NodeAdminFormPresenter.new(node_id: node.id)
    @following_form = FollowingFormPresenter.new
    if request.request_method_symbol == :post
      NodeAdminFormPresenter.new(params[:node_admin_form_presenter]).save
    end
    respond_with node
  end

  def up 
    authorize! :update, node
    node.move_higher
    redirect_to node.parent
  end 

  def down
    authorize! :update, node
    node.move_lower
    redirect_to node.parent
  end

  private
  def node
    @node ||= current_space.nodes.find(params[:id])
  end

  def service
    @service ||= NodeService.new(current_user, current_space)
  end

  def node_params
    params.require(:node).permit(
      :parent_id, :title, :body, :prototype_id, :image_url, :document,
      :email, :telephone, :map_address, :url)
  end
end

app/helpers/node_helper.rb
module NodeHelper 
  def render_body(node, options = {})
    return unless node.body.present?
    text = options[:length] ?
      HTML_Truncator.truncate(node.body, 40) :
      node.body

    text = Linkify.links(text) do |tag, name, param|
      link_to(name, node_path(param), class: 'linkify')
    end

    Rinku.auto_link(
      text, :urls, 'target="_blank" rel="nofollow"').html_safe
  end

  def node_image(node)
    node.image.url || node.dropbox_image_url
  end

  def image_source(node)
    node.image.url ? 'local' : 'remote'
  end

  def main_node?(node)
    node.parent.blank? || current_page?(node)
  end

  def children_name(node)
    node.proto.children.try(:name)
  end

  def cancel_form_node_path(node)
    if !node.new_record?
      node_path(node)
    elsif node.parent
      node_path(node.parent)
    else
      root_path
    end
  end

end

app/views/nodes/_actions.html.slim
div.node-main-actions
  =' link_to 'Editar', [:edit, node],
    class: 'pure-button' 
  - if node.proto.children
    =' link_to "Añadir #{children_name(node)}", 
      new_node_path(p: node, proto: node.proto.children_id),
      class: 'pure-button pure-button-secondary'
  - if has_photos?(node)
    =' link_to icon(:picture, 'Subir fotos'),
      new_photo_path(n: node.id),
      class: 'pure-button' 
  - if has_tasks?(node)
    =' link_to icon('circle-blank', 'Tarea'),
        node_task_path(node),
        class: 'pure-button' 
  - if has_document?(node)
    =' link_to icon('upload', 'PDF'),
       node_document_path(node),
       class: 'pure-button' 
  - if has_event?(node)
    - if node.event
      =' link_to icon('calendar', 'Editar evento'),
          edit_event_path(node.event),
          class: 'pure-button'
    - else
      =' link_to icon('calendar', 'Añadir al calendario'),
        new_node_event_path(node), class: 'pure-button'
  - if current_user && current_user.admin?
    =' link_to icon('magic', "Editar '#{node.proto.name}'"),
      [:edit, node.proto], class: 'pure-button'

app/views/nodes/_ancestors.html.slim
- if node.ancestors.size > 0
  div.node-ancestors
    - node.ancestors.each do |parent|
      span =' link_to icon('arrow-right', parent.title), parent 

app/views/nodes/_child.html.slim
= div_for node, class: "child" do
  div.counter = node.children_count
  - if node.title?
    h2.title == link_to_unless_current node.title, node

  div.content
    - if node.image?
      div.node_image = image_tag node.image.url
    - if node.body?
      div.body = simple_format(node.body)

div.node_info
  ' Por #{link_to node.user.name, node.user} 
  ' el #{l node.created_at, format: :short} 
  ' (#{node.position})

  div.actions
    =' link_to 'Editar', [:edit, node]
    =' link_to 'Borrar', node, method: :delete,
      data: { confirm: "¿Quieres borrar '#{node.title}'?" }
    =' link_to 'Subir', [:up, node], method: :put
    =' link_to 'Bajar', [:down, node], method: :put

app/views/nodes/_document.html.slim
- if node.document?
  b = link_to icon('download', 'Descargar PDF'), node.document.url

app/views/nodes/_following.html.slim
div.followers
  - if following = Following.following(@node, current_user)
    span.follower = icon('ok', 'Estás siguiendo esta página. ')
    ' Recibirás un email cuando cambie. 
    = link_to 'Dejar de seguir', following, method: :delete,
      data: { confirm: "¿Quieres dejar de seguir #{@node.label}?",
      action: 'unfollow' }, class: 'unfollow'
  - else
    =' link_to icon('eye-open', 'Hazte seguidor/a de esta página'), 
      followings_path(n: @node.id), method: :post,
      class: 'follow' 
    | si quieres recibir emails cuando alguien haga cambios.

app/views/nodes/_form_photo.html.slim
= simple_form_for UploadPhotoFormPresenter.new(node_id: @node.id),
  url: photos_path do |form|
  = form.input :node_id, as: :hidden
  //h3 Sube una imágen desde tu dropbox:
  //input[type="dropbox-chooser" name="selected-file"
    style="visibility: hidden;" data-link-type="direct"]
  //h3 O desde tu ordenador:
  = form.input :image, as: :file, label: false
  = form.submit 'Subir foto', 
    class: 'pure-button pure-button-primary'

app/views/nodes/_main.html.slim
div.main
  - if node_image(node).present?
    div.node_image.image
      = image_tag node_image(node), 
        class: "lightbox #{image_source(node)}"
  - else
    div.node_image.no-image
  
  - if node.body?
    div.body.hashtags = format_body(node.body)
  - if node.document?
    div.download = link_to(icon('download', 'Descargar PDF'), node.document.url) 

- if node.mentions_count > 0
  div.info.mentions_to
    ' Menciona a: 
    - node.mentioned_nodes.each do |mn|
      =' link_to truncate(mn.label), mn, class: 'linkify'

- if node.mentioned_count > 0
  div.info.mentioned_by
    ' Mencionado en: 
    - node.mentioned_by_nodes.each do |mn|
      =' link_to truncate(mn.label), mn, class: 'linkify'

app/views/nodes/_mentioned.html.slim
div.node-mentioned.separator
  h4 Sobre #{node.title}, ver también:
  = render 'nodes/navigation', nodes: node.mentioned_by_nodes
  = render 'nodes/navigation', nodes: node.mentioned_nodes

app/views/nodes/_navigation.html.slim
ul.navigation.unstyled
  - nodes.each do |n|
    = cache ['nodenav', n] do
      li.nodenav
        span.nodenav-title =' link_to arrow(n.title), n
        - if n.event
          span.nodenav-event 
            = icon('calendar')
            =' link_to l(n.event.date), event_calendar_path(n.event)
            = n.event.time if n.event.time?
        - if n.email?
          span <i class='icon-envelope'></i>#{n.email} 
        - if n.telephone?
          span <i class='icon-phone'></i>#{n.telephone} 
        - if n.map_address?
          span.nodenav-address 
            = icon('map-marker')
            = link_to n.map_address, map_path
        = render 'nodes/document', node: n

app/views/nodes/_node.html.slim
= cache ['node', node]
  = div_for node, class: 'node-main' do
    h1
      = link_to_unless_current node do
        = node.title
    = render('nodes/event', event: node.event) if node.event
    - if node.url?
      h4.url = link_to node.url, node.url, target: '_blank'

    - if node.image_url?
      div class="node-main-image #{node.image_style}"
        = image_tag(node.image_url, alt: node.title,
          class: 'lightbox')

    - if has_body?(node)
      div.node-main-body
        = render_body(node)

    div.node-main-document
      = render 'nodes/document', node: node

    div.node-main-map
      = render 'nodes/contact', node: node

    

app/views/nodes/_node_title.html.slim
div.ancestors
  - node.ancestors.each do |parent|
    span =' link_to icon('arrow-right', parent.title), parent 

app/views/nodes/edit.html.slim
- title "Editar '#{@node.title}'"

= render 'form', node: @node

div.delete_node.separator
  =' link_to icon(:trash, 'Borrar'), @node, method: :delete,
    data: { confirm: "¿Quieres borrar '#{@node.title}'?" },
    class: 'pure-button pure-button-error'
  | Puedes borrar esta página, pero espero que
    sea por un buen motivo

app/views/nodes/new.html.slim
- if @node.prototype
  = title "Añadir #{@node.prototype.name}" 
- else
  = title 'Añadir página'

= render 'form'

app/views/nodes/show.html.slim
- presenter = NodePresenter.new(@node, self)
- title(@node.title)

= render 'ancestors', node: @node
= presenter.render_node
= render 'actions', node: @node

= presenter.render_photos


- if has_comments?(@node)
  = render 'comments/comments', node: @node

= presenter.render_children
= presenter.render_mentioned


//div.separator
//  = render 'following'

<script type="text/javascript" src="https://www.dropbox.com/static/api/1/dropins.js" id="dropboxjs" data-app-key="97zrc4q9b8q6ilx"></script>  