config/routes.rb
require 'sidekiq/web'
Liki::Application.routes.draw do

  root to: 'nodes#root'

  concern :position do
    put :up, on: :member
    put :down, on: :member
  end

  resources :nodes, concerns: :position, path: 'p' do
    get :admin, on: :member
    post :admin, on: :member
    resources :nodes, path: 'p', only: :new
    resources :followings, path: 'f', only: :index
    resource :document, path: 'doc'
    resource :task, path: 'tarea'
    resource :event, path: 'evento', only: [:show, :new]
    resources :comments, path: 'comentarios'
  end

  resources :users, path: 'u'
  resources :members, path: 'm'
  resources :spaces
  resources :activities, path: 'a'
  resources :access
  resources :followings, path: 'f', only: [:create, :destroy]
  resources :photos, path: 'fotos'
  resources :photo_tags, path: 'ptag'
  resources :prototypes, path: 'tipos'

  get '/calendario(/:y(/:m))' => 'events#index', as: :calendar,
    constraints: {y: /\d{4}/, m: /\d{1,2}/}
  resources :events, path: 'calendario', except: [:index]
  get 'mapa' => 'explorer#map', as: :map


  resource :inbox, controller: 'inbox', only: [:show,:create]

  get 'novedades' => 'nodes#index', as: :recent
  get 'buscar' => 'explorer#search', as: :search

  resources :sessions, path: 's'
  get 'entrar(/:id)' => 'sessions#new', as: :login
  get 'salir' => 'sessions#destroy', as: :logout
  get 'enter/:id', to: 'sessions#enter', as: :enter
  get 'user_level/:id', to: 'sessions#user_level'
  get 'visit/:id', to: 'sessions#visit', as: :visit
  post 'invitacion', to: 'sessions#send_token', as: :send_token

  mount Sidekiq::Web, at: '/sidekiq'

  get '404' => 'site#error404'
  get '500' => 'site#error500'
  get 'mmmm', to: 'site#access_denied', as: :access_denied
end

app/models/space.rb
class Space < ActiveRecord::Base
  belongs_to :user
  belongs_to :node
  belongs_to :photos_node, class_name: 'Node'
  has_many :mentions
  has_many :nodes
  has_many :photos
  has_many :followings, as: :followed, dependent: :delete_all
  has_many :followers, through: :followings, source: :user, class_name: 'User'
  has_many :activities, -> { order('updated_at DESC') }
  has_many :prototypes, -> { order('name ASC') }
  has_many :events, -> { order('date ASC') }

  include HasMembers

  validates_presence_of :name, :user_id, :email

  mount_uploader :background_image, SpaceImageUploader

  after_create :create_space_node

  def default_prototype
    @proto = prototypes.first ? prototypes.order('id ASC').first :
      prototypes.create(name: 'Página')
  end

  protected
  def create_space_node
    self.node = Node.create(title: self.name, body: self.name,
                            user: self.user, space: self)
    self.save
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  respond_to :html
  before_filter :require_admin

  def index
    @spaces = Space.order('name ASC')
    respond_with @spaces
  end

  def new
    @space = Space.new
    respond_with @space
  end

  def edit
    respond_with space
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    @space.save
    @space.member(current_user)
    respond_with @space, location: spaces_path
  end

  def update
    space.attributes = space_params
    space.save
    service.regenerate_counters if params[:regenerate_counters].present?
    service.regenerate_mentions if params[:regenerate_mentions].present?
    respond_with space, location: spaces_path
  end

  def show
    redirect_to current_space.node
  end

  protected
  def space
    @space ||= Space.find params[:id]
  end

  def space_params
    params.require(:space).permit(
      :name, :host, :email, 
      :photos_node_id,
      :is_open, :background_image,
      :has_wiki, :has_calendar, :has_photos, :has_map)
  end

  def service
    @service ||= SpaceService.new(current_space)
  end

end

app/views/spaces/_form.html.slim
= simple_form_for @space do |form|
  = form.input :name
  = form.input :host
  = form.input :email
  = form.input :is_open
  = form.input :background_image
  = form.input :photos_node_id
  - [:wiki, :calendar, :photos, :map].each do |service|
    = form.input "has_#{service}"


  = boolean_input(:regenerate_counters, 'Regenerar estadísticas')
  = boolean_input(:regenerate_mentions, 'Regenerar menciones')
  = form.submit class: 'pure-button'

app/views/spaces/edit.html.slim
div.node
  = title "Editar #{@space.name}"
  = render 'form'

app/views/spaces/index.html.slim
= title 'Espacios'

- @spaces.each do |space|
  = div_for space do
    h2 
      =' space.name 
      small = icon(space.is_open? ? 'unlock' : 'lock')
    h4 = link_to space.host, Rails.env.production? ? 'space.host' : visit_path(id: space.name)
    p
      ' Páginas: #{space.nodes_count} 
      ' / Menciones: #{space.mentions_count}
      ' / Participantes: #{space.members_count}
      ' / Seguidores: #{space.followers_count}

    - if following = Following.following(space, current_user)
      = link_to icon('eye-close', 'Dejar de seguir'), following,
        method: :delete, data: { confirm: '¡¿Seguro?!' }
    - else
      = link_to icon('eye-open', 'Seguir'), 
        followings_path(s: space.id), method: :post

  div.actions
    = link_to icon(:pencil, 'Editar'), edit_space_path(space),
      class: 'pure-button'

app/views/spaces/new.html.slim
div.node 
  = title 'Añadir espacio'
  = render 'form'